code --install-extension amih90.to
code --install-extension Angular.ng-template
code --install-extension dbaeumer.vscode-eslint
code --install-extension dkultasev.vs-code-snippet-generator
code --install-extension ebrithil30.vscode-ts-auto-return-type
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension fkrull.gtk-dark-titlebar
code --install-extension hancel.google-translate
code --install-extension ionutvmi.path-autocomplete
code --install-extension john-crowson.angular-file-changer
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension mhutchie.git-graph
code --install-extension milab.vscode-theme-adwaita-like
code --install-extension ms-azuretools.vscode-docker
code --install-extension natewallace.angular2-inline
code --install-extension P-de-Jong.vscode-html-scss
code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sndst00m.vscode-native-svg-preview
code --install-extension stackbreak.comment-divider
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-french
code --install-extension Tyriar.lorem-ipsum
code --install-extension ue.alphabetical-sorter
code --install-extension vismalietuva.vscode-angular-support
code --install-extension vit-m.template-strings
code --install-extension whtouche.vscode-js-console-utils
code --install-extension yzhang.markdown-all-in-one
code --install-extension ZaferAYAN.lorem-picsum
