code --install-extension Angular.ng-template
code --install-extension bierner.emojisense
code --install-extension dkultasev.vs-code-snippet-generator
code --install-extension EditorConfig.EditorConfig
code --install-extension erhise.vs-ng-quick-switch
code --install-extension esbenp.prettier-vscode
code --install-extension fkrull.gtk-dark-titlebar
code --install-extension funkyremi.vscode-google-translate
code --install-extension ionutvmi.path-autocomplete
code --install-extension johnpapa.Angular2
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension mhutchie.git-graph
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension natewallace.angular2-inline
code --install-extension natqe.reload
code --install-extension P-de-Jong.vscode-html-scss
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension rebornix.project-snippets
code --install-extension stackbreak.comment-divider
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-french
code --install-extension stylelint.vscode-stylelint
code --install-extension Tyriar.lorem-ipsum
code --install-extension vismalietuva.vscode-angular-support
code --install-extension vit-m.template-strings
code --install-extension whtouche.vscode-js-console-utils
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yatki.vscode-surround
code --install-extension yzhang.markdown-all-in-one
