code --install-extension a-h.templ
code --install-extension alexdauenhauer.catppuccin-noctis-icons
code --install-extension amih90.to
code --install-extension angular.ng-template
code --install-extension biomejs.biome
code --install-extension bradlc.vscode-tailwindcss
code --install-extension cardinal90.multi-cursor-case-preserve
code --install-extension catppuccin.catppuccin-vsc
code --install-extension dkultasev.vs-code-snippet-generator
code --install-extension dotcypress.console-log
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension golang.go
code --install-extension guilhermetheodoro.typescript-indexing
code --install-extension hancel.google-translate
code --install-extension ionutvmi.path-autocomplete
code --install-extension john-crowson.angular-file-changer
code --install-extension johnpapa.angular2
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension lsl.vscode-templ-go-to-definition
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.remote-explorer
code --install-extension pflannery.vscode-versionlens
code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension pomdtr.excalidraw-editor
code --install-extension pushqrdx.inline-html
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sndst00m.vscode-native-svg-preview
code --install-extension starfederation.datastar-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-french
code --install-extension supermaven.supermaven
code --install-extension tamasfe.even-better-toml
code --install-extension ue.alphabetical-sorter
code --install-extension usernamehw.errorlens
code --install-extension vit-m.template-strings
code --install-extension wwwalkerrun.nativescript-ng2-snippets
code --install-extension yoavbls.pretty-ts-errors
