start-at-login = true

after-startup-command = [
    # JankyBorder integration
    'exec-and-forget /usr/local/bin/borders active_color=0xff7287fd inactive_color=0xff4c4f69 width=7',
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 4
outer.bottom = 4
outer.top = 4
outer.right = 4

[mode.main.binding]
ctrl-left = 'focus --boundaries-action wrap-around-the-workspace left'
ctrl-down = 'focus --boundaries-action wrap-around-the-workspace down'
ctrl-up = 'focus --boundaries-action wrap-around-the-workspace up'
ctrl-right = 'focus --boundaries-action wrap-around-the-workspace right'

ctrl-shift-left = 'move left'
ctrl-shift-down = 'move down'
ctrl-shift-up = 'move up'
ctrl-shift-right = 'move right'

ctrl-shift-h = 'join-with up'
ctrl-shift-v = 'join-with left'

ctrl-f = 'fullscreen'
ctrl-s = 'layout v_accordion'               # 'layout stacking' in i3
ctrl-w = 'layout h_accordion'               # 'layout tabbed' in i3
ctrl-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3
ctrl-shift-space = 'layout floating tiling' # 'floating toggle' in i3

ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
alt-tab = 'workspace-back-and-forth'
ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'

ctrl-r = 'mode resize'
[mode.resize.binding]
left = 'resize width -50'
down = 'resize height +50'
up = 'resize height -50'
right = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

# List of applications ids here: https://nikitabobko.github.io/AeroSpace/goodies#popular-apps-ids
[[on-window-detected]]
check-further-callbacks = true
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['layout tiling', 'move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = ['layout tiling', 'move-node-to-workspace 2']
