"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$os$hostname[](fg:white bg:bright-black)[█](fg:bright-black bg:black)$directory[█](fg:bright-black bg:black)[$git_branch$git_state$git_status](bold bg:black fg:white)[█](fg:black)$nodejs$c$golang$php$python
$character
"""

[os]
disabled = false
style = "fg:bright-white bg:black inverted bold"
[os.symbols]
NixOS = " "
Ubuntu = "󰕈"
Windows = ""
SUSE = ""
Raspbian = "󰐿"
Macos = "󰀵"
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Arch = "󰣇"
Debian = "󰣚"
Redhat = "󱄛"

[hostname]
ssh_only = false
style = "fg:bright-white bg:black inverted bold"
format = "[█](fg:bright-white bg:black)[$hostname]($style)[](fg:bright-white bg:white)"

[username]
show_always = true
style_user = "fg:bright-white bg:black inverted bold"
style_root = "fg:bright-white bg:black inverted bold"
format = "[█](fg:bright-white bg:black)[ $user]($style)[](fg:bright-white bg:white)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style)"
style = "bold fg:bright-white bg:bright-black"
read_only = "󰌾 "
read_only_style = "bold white"
home_symbol = "~"
[directory.substitutions]
Documents = "󰉌  Documents"
Downloads = "󰉍  Downloads"
Music = "󱍙  Music"
Pictures = "󰉏  Pictures"
Projects = "󱃪  Projects"
Setup = "  Setup"

[character]
format = "$symbol"
error_symbol = "[ ](fg:red)"
success_symbol = "[  ](fg:green)"

[git_commit]
commit_hash_length = 8
style = "white"
tag_symbol = ""

[git_branch]
format = " 󰘬 $branch"
style = "bold fg:bright-black bg:black"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "bold fg:bright-black bg:black"
conflicted = "  $count"
deleted = "  $count"
modified = "  $count"
stashed = "  $count"
staged = "  $count"
renamed = "  $count"
untracked = "  $count"

[git_state]
format = "[($state( $progress_current / $progress_total))]($style)"

[nodejs]
symbol = ""
style = "fg:green"
format = " [$symbol $version]($style)"

[c]
symbol = " "
style = "fg:blue"
format = " [$symbol $version]($style)"

[rust]
symbol = ""
style = "fg:orange"
format = " [$symbol $version]($style)"

[golang]
symbol = ""
style = "fg:cyan"
format = " [$symbol $version]($style)"

[php]
symbol = ""
style = "fg:blue"
format = " [$symbol $version]($style)"

[python]
symbol = ""
style = "fg:yellow"
format = " [$symbol $version]($style)"
